version: 2
jobs:
  build:
    docker:
      - image: selenium/standalone-chrome:latest
    environment:
        GRADLE_USER_HOME: .gradle-home
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home
      - run:
          command: |
            ./gradlew runTests -Dbrowser=chrome -Dbrowser.option=headless
      - store_artifacts:
          path: build/reports
      - save_cache:
          key: gradle-home
          paths:
            - .gradle-home
      - store_test_results:
          path: build/reports/     
