version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0-browsers
    environment:
        GRADLE_USER_HOME: .gradle-home
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: |
          node --version
          java --version
          google-chrome --version
      - restore_cache:
          keys:
            - gradle-home
      - run:
          command: |
            ./gradlew runTests -Dbrowser=chrome -Dbrowser.option=headless
      - store_artifacts:
          path: build/reports
      - save_cache:
          key: gradle-home
          paths:
            - .gradle-home
