name: Regression Tests - Chrome

on: [ workflow_dispatch ]

jobs:
  Run_Regression_Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Run Tests
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: runTests -Dbrowser=chrome -Dbrowser.option=headless -Dtags=@regression

      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/reports/cucumber.xml'

      - name: Get Allure Report history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: reports
          path: reports/regression

      - name: Build Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: reports/regression
          allure_report: regression/allure-report
          allure_history: regression/allure-history
          keep_reports: 20
          subfolder: regression

      - name: Deploy Allure report to Github Pages into the regression dir
        if: always()
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: reports
          publish_dir: regression/allure-history
          keep_files: true