name: Regression Tests - Chrome

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 5 1-12 *'

jobs:
  Run_Regression_Tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17

      - name: Validate Gradle wrapper
        uses: gradle/gradle-build-action@v3

      - name: Run Tests
        run: >-
          ./gradlew test
          -Dbrowser=chrome 
          -Dbrowser.option=headless 
          -Dtags=@regression

      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/reports/cucumber.xml'

      - name: Get Allure Report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: reports
          path: reports/regression

      - name: Build Allure Report
        uses: simple-elf/allure-report-action@v1.6
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: reports/regression
          allure_report: regression/allure-report
          allure_history: regression/allure-history
          keep_reports: 20
          subfolder: regression

      - name: Deploy Allure report to Github Pages into the regression dir
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: reports
          publish_dir: regression/allure-history
          keep_files: true