name: Smoke Tests - Chrome

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  Run_Smoke_Tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          distribution: adopt
          java-version: 17

      - name: Validate Gradle wrapper
        uses: gradle/gradle-build-action@v2.4.0

      - name: Run Tests
        run: >-
          ./gradlew test
          -Dbrowser=chrome 
          -Dbrowser.option=headless 
          -Dtags=@smoke

      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v3.7.5
        if: always()
        with:
          report_paths: '**/build/reports/cucumber.xml'

      - name: Get Allure Report history
        uses: actions/checkout@v3.3.0
        if: always()
        continue-on-error: true
        with:
          ref: reports
          path: reports/smoke

      - name: Build Allure Report
        uses: simple-elf/allure-report-action@v1.6
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: reports/smoke
          allure_report: smoke/allure-report
          allure_history: smoke/allure-history
          keep_reports: 20
          subfolder: smoke

      - name: Deploy Allure report to Github Pages in the Smoke dir
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: reports
          publish_dir: smoke/allure-history
          keep_files: true